#!/bin/bash

# put arguments in array to preserve single quotes
REGEX=("${1}")

# long way
#grep -nri --color=auto --include *.app.src --include "*.config*" --include "Makefile*" "${REGEX[@]}"

# note that "echo a{b,c}" spits out "ab ac" and the substitution is done by the shell before grep sees it
grep -nri --color=auto --include={*.app.src,*.config,Makefile} "${REGEX[@]}"
