#!/bin/bash

# Do a raw grep in src
# - .erl, .hrl and .ex files
# - include tests
# - exclude dependencies

# put arguments in array to preserve single quotes
REGEX=("${1}")
grep -nr --color=auto --include="*.?rl" --include="*.ex*" --exclude-dir="deps" "${REGEX[@]}"
