#!/bin/bash

# Do a raw grep in src
# - .erl, .hrl and .ex files
# - exclude tests
# - exclude dependencies

# put arguments in array to preserve single quotes
REGEX=("${1}")

# note that "echo a{b,c}" spits out "ab ac" and the substitution is done by the shell before grep sees it
grep -nr --color=auto --include=*.{?rl,ex} --exclude-dir={.*,test,deps,_rel,logs} "${REGEX[@]}"
