#!/bin/bash

# put arguments in array to preserve single quotes
REGEX=("${1}")
grep --line-number \
     --recursive \
     --color=auto \
     --exclude-dir="release-3.*" \
     --exclude-dir="old" \
     --include="*.sql" "${REGEX[@]}"
