#!/bin/bash

# put arguments in array to preserve single quotes
REGEX=("${1}")
grep --line-number \
     --recursive \
     --color=auto \
     --exclude-dir={release-3.*,old} \
     --include="*.sql" "${REGEX[@]}"
# note that "echo a{b,c}" spits out "ab ac" and the substitution is done by the shell before grep sees it
